[project]
name = "arxiv-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "scikit-learn",
    "datasets>=4.4.1",
    "modal>=1.2.5",
    "pandas>=2.3.3",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]
